# Generated by Django 4.2 on 2023-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
